golang/filesystem/managedItem.go
golang/filesystem/managedItem_test.go
golang/managedItem.go

Composite branch implemented and tested

Feature managed file composite

---

golang/filesystem/directoryToComposite.go
golang/filesystem/directoryToComposite_test.go
golang/filesystem/managedItem.go

Implemented and tested.
Note: I added a new function to the managedItem file for displlaying the composite only for testing purposes
also accidently added myself as assignee and it does not want to remove me

Feature directory to composite 

---

python/Dockerfile
python/testing/test_grpc_server.py
python/testing/test_kw_extractor.py

Changed some of the new tests to use directories relative to the current file since the file were not found when running from a container.

Fixed Dockerfile by slightly modifying some tests

---

.github/workflows/actions.yml
docker-compose.yml
golang/Dockerfile
python/Dockerfile

* Dockerfile(s)
* Docker compose
* Actions.yml for CICD

Cicd final

---

python/src/kw_extractor.py
python/src/master.py
python/src/metadata_scraper.py
python/testing/test_kw_extractor.py
python/testing/test_metadata_scrape.py

* Description: Refactored master.py to extract metadata and keywords to a files list. Updated tests to work with refactored code.
* Type: Refactor
* Scope: The process function of Master 
* Instead of looping through a directory request and appending metadata we needed to loop through and create a list of files. This list needed to contain the metadata and the keywords.

Python Master Refactor And Metadata / Keyword extraction 

---

python/src/kw_extractor.py
python/src/master.py
python/src/metadata_scraper.py

* Changed: Missing import added from merge conflict. Removed unused imports.

Fixed merge conflict problem and removed unused imports

---

python/src/directory_builder.py
python/src/k_means.py
python/src/master.py

- **Description**: _Need to transform kmeans labels back into a response_
- **Summary**: _Clusters recursively and builds a DirectoryResponse to send back to Go. Theres a few parameters to control initial directory count, minimum leaf size etc._
- **Usage**: _Must supply a directory request with metadata attached and kmeans cluster will return the DirectoryResponse._
- **Input → Output**: 
```
files =[
{metadata, full_vector},
...
]
```
```
Directory_0/
Directory_0_1_1/
Directory_0_1_1_1_2/
- Apr8TODO.txt
- COS221 Assignment 1 2025.pdf
- Prac1Triggers.txt
Directory_0_1_1_0_2/
Directory_0_1_1_0_2_1_3/
- Apr18 meeting.txt
- COS 301 - Mini-Project - Demo 1 Instructions.pdf
- COS 301 - Mini-Project - Demo 2 Instructions.pdf
- Importing the Database.md
- MP Progress report.txt
- …
```

Python feature clusterlabel to directory

---

python/testing/test_directory_builder.py

- **Description**: _Testing was needed for this section_
- **Tests Added**: _test_directory_builder.py_
- **Coverage**: _Covers all functionality of the directory builder._
- **Run**: ```make python_test```

Unit and integration tests - Directory Builder

---

makefile
python/src/full_vector.py
python/src/kw_extractor.py
python/testing/test_fullvector.py
python/testing/test_kw_extractor.py

- **Tests Added**:  Unit testing for the full vector class
- **Coverage**:  Creating a full vector from a files list. All Helper methods in full_vector
- **Why?**:  No unit testing had been done for full_vector thus far
- **Run**:  Will run with ``` make python_test ``` alternatively ``` pytest -v -s --color=yes --tb=short python/testing/test_fullvector.py``` from root directory.
- I changed kw_extractor and full_vector slightly to somewhat improve clustering performance.

Python test and improve

---

docs/documentation/demo_2/api.md
golang/filesystem/server.go
golang/filesystem/startUp_handler.go
golang/filesystem/startUp_test.go
golang/storage/main.json
makefile

please note the current json file contains routes specific to my computer

Go feature storing composites

---

golang/filesystem/startUp_handler.go
golang/storage/main.json

simple 1 line change. startUp now resets memory to not dual load managers

reset composites each time startup is called

---

docs/documentation/demo_2/api.md
golang/filesystem/directoryToObject.go
golang/filesystem/directoryToObject_test.go
golang/filesystem/handler_loadTree.go
golang/filesystem/managedItem.go
golang/filesystem/managedItem_test.go
golang/filesystem/server.go
golang/filesystem/server_test.go

Fixed locking as there were some bugs that I had missed.
Also updated docs to reflect changes

Go hot fix locking

---

app/lib/api.dart
app/lib/custom_widgets/duplicate_dialog.dart
app/lib/custom_widgets/file_details_panel.dart
app/lib/custom_widgets/hoverable_button.dart
app/lib/custom_widgets/tag_dialog.dart
app/lib/models/duplicate_model.dart
app/lib/models/file_tree_node.dart
app/lib/pages/manager_page.dart
app/lib/pages/manager_page_sub/folder_view_page.dart
app/lib/pages/manager_page_sub/graph_view_page.dart
app/pubspec.lock
app/pubspec.yaml
app/test/unit_test.dart

- **Description**: Implemented endpoints, locking, unlocking, duplicates
- **Type**: Features
---
- **Summary**: User able to lock and unlock files/folders
- **Usage**: Right click on file/folder
- **Before (Feature)**: Was only visual
- **After (Feature)**: Actual locking/unlocking of files
---
- **Summary**: Detects and displays duplicate files
- **Usage**: Click on duplicates button in the nav bar
- **Before (Feature)**: Not possible
- **After (Feature)**: Possible
---
- **Tests Added**: Fixed Test that were broken
---

API Integration to frontend

---

protos/message_structure.proto
python/src/full_vector.py
python/src/kw_extractor.py
python/src/master.py
python/src/request_handler.py
python/testing/test_keywords_request.py

- **Description**: Added gRPC endpoint to allow user to get keywords extracted for set of files
- **Type**:  Feature
- **Summary**: Given a set of files, returns keyword and associated scrore
- **Usage**: Set request type to KEYWORDS
- **Input → Output**:
```
root_dir = Directory(
name = "test_files_3",
path = get_path("test_files_3"),
files = files1,
)    
req = DirectoryRequest(root=root_dir, requestType="KEYWORDS")
```
```
// Example 
Week 5_Tutorial_2024_with answers: [keyword: "probability"
score: 0.00682882126
, keyword: "distribution"
score: 0.0108785192
, keyword: "binomial"
```

Python feature keyword endpoint

---

app/lib/api.dart
app/lib/custom_widgets/custom_dropdown_menu.dart
app/lib/custom_widgets/custom_search_bar.dart
app/lib/custom_widgets/hoverable_button.dart
app/lib/main.dart
app/lib/navigation/main_navigation.dart
app/lib/navigation/shell.dart
app/lib/pages/advanced_search_page.dart
app/lib/pages/manager_page.dart
app/lib/pages/manager_page_sub/graph_view_page.dart
app/lib/pages/search_sub_page/folder_view_search.dart
golang/storage/main.json

App feature integration search

---

app/lib/api.dart
app/lib/custom_widgets/custom_dropdown_menu.dart
app/lib/custom_widgets/custom_search_bar.dart
app/lib/custom_widgets/hoverable_button.dart
app/lib/main.dart
app/lib/navigation/main_navigation.dart
app/lib/navigation/shell.dart
app/lib/pages/advanced_search_page.dart
app/lib/pages/manager_page.dart
app/lib/pages/manager_page_sub/graph_view_page.dart
app/lib/pages/search_sub_page/folder_view_search.dart
golang/filesystem/bulkOperations.go
golang/filesystem/duplicateFiles.go
golang/filesystem/handler_loadTree.go
golang/filesystem/moveDirectory.go
golang/filesystem/server_test.go
golang/filesystem/startUp_handler.go
golang/main.go
golang/storage/main.json

Sped up load tree by removing unnecessary functions.
Made loading smart managers concurrent for faster loading.
No changes to documentations or tests
Implemented search integration in front-end.
Added boot up screen.

Go speedup tree builder

---

app/lib/custom_widgets/search_item_widget.dart
app/lib/models/file_tree_node.dart
app/lib/navigation/shell.dart
app/lib/pages/advanced_search_page.dart
app/lib/pages/manager_page.dart
app/lib/pages/search_sub_page/folder_view_search.dart
golang/filesystem/handler_loadTree.go
golang/storage/main.json

- Shows a list view instead of grid view
- Allows users to see path of file in search results
- Right clcik and go to file folder location feature implemented
- *Note* Advanced search UI still needs to be finalised

App feature search UI

---

app/lib/api.dart
app/lib/custom_widgets/bulk_dialog.dart
app/lib/models/file_model.dart
app/lib/navigation/main_navigation.dart
app/lib/navigation/shell.dart
app/lib/pages/manager_page.dart
app/lib/pages/manager_page_sub/folder_view_page.dart
app/lib/pages/manager_page_sub/graph_view_page.dart
app/lib/pages/smart_managers_page.dart
golang/filesystem/bulkOperations.go
golang/filesystem/bulkOperations_test.go
golang/filesystem/handler_loadTree.go
golang/filesystem/moveDirectory.go
golang/filesystem/moveDirectory_test.go
golang/filesystem/server.go
golang/filesystem/server_test.go

Integration of front-end and return types and bulk operations on Golang.

Go integration branch

---

golang/filesystem/handler_loadTree.go
golang/filesystem/handler_search.go
golang/filesystem/moveDirectory.go
golang/filesystem/startUp_handler.go
python/src/directory_builder.py

fixed the keywords not extracting consistently and the stats pages.
team effort. we are all a member of go team tonight

Go hotfix storage and keywords

---

golang/filesystem/handler_keywordSearch.go
golang/filesystem/handler_loadTree.go
golang/filesystem/tests/keyword_search_test.go

appends pthons keywords to gos to have keywords for more files

Go fix python keyword overwrite

---

app/lib/main.dart
golang/filesystem/bulkOperations.go
golang/filesystem/handler_loadTree.go
golang/filesystem/handler_search.go
golang/filesystem/moveDirectory.go
golang/filesystem/saveComposite.go
golang/filesystem/server.go
golang/filesystem/statistics.go

Go hotfix storage stats

---

app/lib/custom_widgets/file_item_widget.dart
app/lib/pages/advanced_search_page.dart
app/lib/pages/manager_page_sub/graph_view_page.dart

- Removed text if no manager is selected on advanced search page.
- Made text more visible on the graph view page.
- Added different icons for different file types.

App python hotfix

---

golang/filesystem/statistics.go
golang/filesystem/tests/saveComposite_test.go

Made return stats safer

---

makefile
protos/message_structure.proto
python/src/create_folder_name.py
python/src/k_means.py
python/src/master.py
python/testing/test_clustering_request.py
python/testing/test_folder_name_creator.py

- **Summary**: Added argument prefferedCase to CLUSTERING request which dictates case used for folder naming
- **Usage**: prefferedCase should be in ["CAMEL", "PASCAL", "SNAKE", "KEBAB"] and defaults to camelCase
- **Before (Feature)**: _folder names were snake case by default
- **After (Feature)**: User may choose preferred case convention

Python feature folder naming case

---

golang/filesystem/handler_keywordSearch.go
golang/filesystem/handler_loadTree.go
golang/filesystem/handler_search.go
golang/filesystem/moveDirectory.go
golang/filesystem/saveComposite.go
golang/filesystem/server.go
golang/filesystem/server_test.go

secondary sorts results alphabetically. 
improvement to search results matching using dynamic closeness requirements
added some testing.
cleaned up some comments and print statements

Go order search results

---

makefile
python/non_functional_tests/test_reliability.py

- **Tests Added**: Reliability test
- **Coverage**: Ensures sorting does not break file integrity
- **Why?**: Added as additional non functional test
- **Run**: ```make python_non_functional```

Added reliability test

---

.github/workflows/actions.yml
golang/filesystem/moveDirectory_test.go

- **Changes**: Modified workflow file to be able to access server secrets
- **Why**:  CI/CD pipeline for demo4

Cicd demo 4
